[package]
name = 'aoc2024'
version = '0.1.0'
edition = '2021'

[dependencies]
unicode-segmentation = '*'
tracing-subscriber = '*'
tracing = '*'
paste = '*'
fnv = '*'
num = '*'
itertools = '*'
logos = '*'
